// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: u4Y4MGpSRpZo7PLABQqvDf
// Component: 9-Ed6s5bD5Aa

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariants_7St0N8Nhl3H } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 7st0n8_nhl3h/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_tailwind_3_4_colors_css from "../library_tailwind_3_4_color_tokens/plasmic.module.css"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: u4Y4MGpSRpZo7PLABQqvDf/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: 9-Ed6s5bD5Aa/css

import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: V_LDpAde5ASU/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: ZSznElQVgbO0/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: csp9Mky7zu_0/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: avRa0qBamuGy/icon

createPlasmicElementProxy;

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"div">;
  aboutUs?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"div">;
  aboutUsBanner?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  ourTeamSection?: Flex__<"div">;
  columns?: Flex__<"div">;
  container?: Flex__<"div">;
  row1?: Flex__<"div">;
  serviceRow?: Flex__<"div">;
  foreground3?: Flex__<"div">;
  button?: Flex__<"button">;
  rowWrapper?: Flex__<"div">;
  colmn1?: Flex__<"div">;
  colmn2?: Flex__<"div">;
  colmn22?: Flex__<"div">;
  colmn3?: Flex__<"div">;
};

export interface DefaultAboutUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_7St0N8Nhl3H()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_tailwind_3_4_colors_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            hasGap={true}
            className={classNames(projectcss.all, sty.header)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wXxM)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__osxVe)}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__lMs10
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qz9Jc)}
                    displayHeight={"78px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"300px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/brrg/images/logoBrassBulletBlueForstickersPng.png",
                      fullWidth: 3429,
                      fullHeight: 974,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cYk90)}
                >
                  <Stack__
                    as={PlasmicLink__}
                    data-plasmic-name={"aboutUs"}
                    data-plasmic-override={overrides.aboutUs}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.aboutUs
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__cuKmX)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vomvc
                      )}
                    >
                      {"About Us"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg___4PbVo)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__h5LT2
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__cOKzl)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eEedf
                      )}
                    >
                      {"Services"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg___54ZnD)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__vi3Gp
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg___2Wro5)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y0AwL
                      )}
                    >
                      {"Clients"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__ndiCm)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__iUg1U
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__uMCo4)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2WteA
                      )}
                    >
                      {"Blog"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__ccPqe)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__hOhvW
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg___5L9Os)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      data-plasmic-name={"contact"}
                      data-plasmic-override={overrides.contact}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.contact
                      )}
                    >
                      {"Contact Us"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__rwzi)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ubrcj)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___8O7YY
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "About US"
                    : "About Us"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vzLfi
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    : "Lorem Ipsum is simply dummy text of the printing and typesetting industry."}
                </div>
              </Stack__>
            </Stack__>
          </div>
          <div
            data-plasmic-name={"ourTeamSection"}
            data-plasmic-override={overrides.ourTeamSection}
            className={classNames(projectcss.all, sty.ourTeamSection)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__dG7T)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__cppqj
                  )}
                >
                  {"Our team"}
                </h2>
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"row1"}
                    data-plasmic-override={overrides.row1}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.row1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__x2DwT)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gLepK
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__xq1Rq)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xqsn2
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__ftrBq
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__wyTbd
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bV53W
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qlXlr
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jsDtr
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__rmDcj
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mtBjs
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__arZzX
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hHyE4
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__zaVki
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___4BbHu
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___451C)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6MOzs
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__kAzoV)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yB5th
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__wSmtm
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__hHDoA
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pq6
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kUi0X
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__kxka
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__zNde3
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___8GgY
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__sVW8
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__onRf
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__yVe78
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__pEy9U
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__cwFw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dwbVz
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__up12T)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wxsDt
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__m4Mkh
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__gkVyV
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fVznx
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7ZWcV
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ip9Mh
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__n3Bb2
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bvtwf
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__qxi5V
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___7T5UD
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__hEpln
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___8WrtZ
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__i9Ry)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2Re1T
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__zXbZi)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fbNdK
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__fTeto
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__ekoAe
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___79RAa
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yVqP
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tHzEh
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__i3RGm
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__esnQ0
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__bR2Nu
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__odCm9
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__oNlO
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__eieVo
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__pFkz1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hnpH1
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__cfHud)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__q0Qnq
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__tPrfO
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__uBqsk
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__m4IVz
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wEbl4
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ioq6
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__hvPwq
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gx92A
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__x1Vkb
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___9MGxX
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__zBxc
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__m3Uys
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__uPfnL)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uGruC
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__dpMOt)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ct9Wh
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__lyeb4
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__ypjVm
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xr80
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vPodR
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qA3Xm
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link___8Dhoe
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__chc2U
                                )}
                                href={"https://www.linkedin.com/"}
                                link={"https://www.linkedin.com/"}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__rDnA
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mtvKa
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__tMPz
                              )}
                              component={Link}
                              platform={"nextjs"}
                            >
                              <Icon3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rm05R
                                )}
                                role={"img"}
                              />
                            </PlasmicLink__>
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                  </Stack__>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__eaQp)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__y35Ss)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__o85Oj)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__f2Aqk)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__wSjDc
                    )}
                  >
                    {"Our values"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qqeJi
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yUrTk)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__a1S)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kTXv6
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__k7BiP
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__l2ZFb
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ywxte
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2J2Uj
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bDoId
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___43DX3)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1SyDe
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__hiC9D
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__egNYf
                            )}
                          >
                            {"Service"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9DzOh
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mZct5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oc1R2
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sj3Vp)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__itevq
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__wbTiE
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__mWwzk
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__emLb
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eiOpD
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__skVdR
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sxo7)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mSXj7
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__rLSsg
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__qDsI2
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kudiy
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dyz3H
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kOdBp
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__dvYfS)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sJuBp
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__gYyks
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__aRGj
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wkLfg
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oUMn5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hvZTe
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ukFzX)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pUeOr
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__jnf8P
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__uhAww
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eqBi4
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dhLml
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qit62
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </Stack__>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__i03Hm)}>
            <div className={classNames(projectcss.all, sty.freeBox__ez7L4)}>
              <div className={classNames(projectcss.all, sty.freeBox__aiA5V)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"foreground3"}
                  data-plasmic-override={overrides.foreground3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.foreground3)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jYm4O)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__qYd4G
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Take your business to the next level"
                        : "Work with us."}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7K4Dt
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Rapidiously revolutionize future-proof niches, and authoritatively \nrestore user-centric e-markets."
                        : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wXcx0)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__o7TSt)}
                    >
                      <Stack__
                        as={"button"}
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          sty.button
                        )}
                      >
                        {false ? (
                          <Icon29Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8E41
                            )}
                            role={"img"}
                          />
                        ) : null}
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tBUkK
                          )}
                        >
                          {"Get IN Touch"}
                        </div>
                        {false ? (
                          <Icon29Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rEj0D
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__qRjhy)}>
            <div className={classNames(projectcss.all, sty.freeBox__bhDl3)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"rowWrapper"}
                data-plasmic-override={overrides.rowWrapper}
                hasGap={true}
                className={classNames(projectcss.all, sty.rowWrapper)}
              >
                <div
                  data-plasmic-name={"colmn1"}
                  data-plasmic-override={overrides.colmn1}
                  className={classNames(projectcss.all, sty.colmn1)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__nuNHg
                    )}
                  >
                    {"About us"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rPg8
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "\u00a9 Company. All rights reserved. This site proudly built with "
                        }
                      </React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__q4Aax
                          )}
                          component={Link}
                          href={"https://www.plasmic.app"}
                          platform={"nextjs"}
                        >
                          {"Plasmic"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{"."}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div
                  data-plasmic-name={"colmn2"}
                  data-plasmic-override={overrides.colmn2}
                  className={classNames(projectcss.all, sty.colmn2)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__zPrDm
                    )}
                  >
                    {"Links"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__gBpy0
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__kLls0
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rf2L
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hVheD
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wvpPt
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </PlasmicLink__>
                </div>
                <div
                  data-plasmic-name={"colmn22"}
                  data-plasmic-override={overrides.colmn22}
                  className={classNames(projectcss.all, sty.colmn22)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__b7LTf
                    )}
                  >
                    {"Nav Links"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2Zww9
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__oRFn
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__yoswY
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__kMpT
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__iYmd3
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </PlasmicLink__>
                </div>
                <div
                  data-plasmic-name={"colmn3"}
                  data-plasmic-override={overrides.colmn3}
                  className={classNames(projectcss.all, sty.colmn3)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__jEAf
                    )}
                  >
                    {"Contact "}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__se2Fj
                    )}
                  >
                    {"1234 Lorem Ipsum .\nLorem Ipsum , GA 30308"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__bAhSr
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"xyz@company.com"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dArxZ
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"1234567890"}
                  </PlasmicLink__>
                </div>
              </Stack__>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUs",
    "contact",
    "aboutUsBanner",
    "foreground2",
    "ourTeamSection",
    "columns",
    "container",
    "row1",
    "serviceRow",
    "foreground3",
    "button",
    "rowWrapper",
    "colmn1",
    "colmn2",
    "colmn22",
    "colmn3"
  ],
  header: ["header", "aboutUs", "contact"],
  aboutUs: ["aboutUs"],
  contact: ["contact"],
  aboutUsBanner: ["aboutUsBanner", "foreground2"],
  foreground2: ["foreground2"],
  ourTeamSection: ["ourTeamSection", "columns", "container", "row1"],
  columns: ["columns", "container", "row1"],
  container: ["container", "row1"],
  row1: ["row1"],
  serviceRow: ["serviceRow"],
  foreground3: ["foreground3", "button"],
  button: ["button"],
  rowWrapper: ["rowWrapper", "colmn1", "colmn2", "colmn22", "colmn3"],
  colmn1: ["colmn1"],
  colmn2: ["colmn2"],
  colmn22: ["colmn22"],
  colmn3: ["colmn3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  aboutUs: "a";
  contact: "div";
  aboutUsBanner: "div";
  foreground2: "div";
  ourTeamSection: "div";
  columns: "div";
  container: "div";
  row1: "div";
  serviceRow: "div";
  foreground3: "div";
  button: "button";
  rowWrapper: "div";
  colmn1: "div";
  colmn2: "div";
  colmn22: "div";
  colmn3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAboutUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUs: makeNodeComponent("aboutUs"),
    contact: makeNodeComponent("contact"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    ourTeamSection: makeNodeComponent("ourTeamSection"),
    columns: makeNodeComponent("columns"),
    container: makeNodeComponent("container"),
    row1: makeNodeComponent("row1"),
    serviceRow: makeNodeComponent("serviceRow"),
    foreground3: makeNodeComponent("foreground3"),
    button: makeNodeComponent("button"),
    rowWrapper: makeNodeComponent("rowWrapper"),
    colmn1: makeNodeComponent("colmn1"),
    colmn2: makeNodeComponent("colmn2"),
    colmn22: makeNodeComponent("colmn22"),
    colmn3: makeNodeComponent("colmn3"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
